name: Validate p3/confs

on:
  pull_request:
    paths:
      - 'p3/confs/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          version: '5.1.0'
      - name: Build kustomize overlay
        run: |
          kustomize build p3/confs/overlays/dev > manifests.yaml
      - name: Validate with kubeval
        uses: garethr/kubeval-action@v2
        with:
          files: manifests.yaml
