apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/usrali2026/alrahmou-p3.git
    targetRevision: HEAD
    path: confs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
