# ─────────────────────────────────────────────
#  Change LOGIN to your 42 login before running
# ─────────────────────────────────────────────
LOGIN = "login"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "#{LOGIN}S" do |server|
    server.vm.hostname = "#{LOGIN}S"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |v|
      v.name   = "#{LOGIN}S"
      v.memory = 1024
      v.cpus   = 1
    end

    server.vm.provision "shell", path: "scripts/install.sh"
  end
end
