Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.provider :libvirt do |v|
    v.cpus = 1
    v.memory = 1024
  end

  config.vm.define "alrahmouS" do |srv|
    srv.vm.hostname = "alrahmouS"
    srv.vm.network "private_network",
      ip: "192.168.56.110",
      libvirt__dhcp_enabled: false

    srv.vm.provision "file", source: "confs", destination: "/home/vagrant/confs"
    srv.vm.provision "shell", path: "scripts/server.sh"
  end
end
